gpu:
  value: 0
dataset:
  value: 'GTEx'
pathway:
  value: ''
model:
  value: 'GAINGTEx'
inplace_mode:
  value: False
sweep:
  value: False
lr:
  desc: Learning rate for optimiser
  value: 0.001
batch_size:
  value: 32
dropout:
  desc: Probability of dropping out a hidden unit
  value: 0.2
lambd_sup:
  value: 1
bn:
  desc: Whether to use batch normalisation
  value: True
m_low:
  desc: Max probability of m
  value: 0.5
m_high:
  desc: Min probability of m
  value: 0.5
epochs:
  desc: Maximum number of epochs to run
  value: 1000
steps_per_epoch:
  desc: Number of train steps per epoch
  value: 100
patience:
  value: 30
nb_layers:
  desc: Number of hidden layers
  value: 4
hdim:
  desc: Hidden dimension of MLPs
  value: 1902
save:
  value: True
save_dir:
  value: '/local/scratch/rv340/gtex_imputation'